const stage=document.getElementById('stage');
const title=document.getElementById('screenTitle');
const modal=document.getElementById('modal');
const helpBtn=document.getElementById('helpBtn');
const navButtons=[...document.querySelectorAll('.nav-btn')];
const state={view:'home',location:'exterior',room:null,settings:loadSettings()};
const rooms=[
  {id:'living-room',name:'Living Room',icon:'🛋️',hint:'Future couch, photos, lamp'},
  {id:'kitchen',name:'Kitchen',icon:'🍽️',hint:'Future table, coffee, calendar'},
  {id:'dads-room',name:"Dad's Room",icon:'🛏️',hint:'Future bed, dresser, mirror'},
  {id:'girls-room',name:"Girls' Room",icon:'🎀',hint:'Future drawings, books, backpacks'},
  {id:'bathroom',name:'Bathroom',icon:'🛁',hint:'Future mirror, towels, shelves'},
  {id:'backyard',name:'Backyard',icon:'🌳',hint:'Future garden, seating, play area'}
];
function loadSettings(){const saved=localStorage.getItem('wh_settings_v01');return saved?JSON.parse(saved):{mode:'auto',sobrietyDate:'2026-01-01',manualDay:1,previewDay:30,previewDate:new Date().toISOString().slice(0,10),tutorialSeen:false};}
function saveSettings(){localStorage.setItem('wh_settings_v01',JSON.stringify(state.settings));}
function daysSober(){if(state.settings.mode==='manual')return Math.max(1,Number(state.settings.manualDay)||1);const start=new Date(state.settings.sobrietyDate+'T00:00:00');const now=new Date();return Math.max(1,Math.floor((now-start)/(1000*60*60*24))+1);}
function setTitle(text){title.textContent=text;}
function setActive(view){navButtons.forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function render(){setActive(state.view); if(state.view==='home')renderHome(); if(state.view==='journal')renderJournal(); if(state.view==='timemachine')renderTimeMachine(); if(state.view==='settings')renderSettings();}
function renderHome(){if(state.location==='exterior')return renderExterior(); if(state.location==='hallway')return renderHallway(); if(state.location==='room')return renderRoom(state.room);}
function renderExterior(){setTitle('Front Porch');stage.innerHTML=`<section class="scene"><div class="sky"></div><div class="sun"></div><div class="house-front"><div class="roof"></div><div class="window w1"></div><div class="window w2"></div><button class="front-door tap-target" id="enterDoor" aria-label="Enter house"></button></div><div class="welcome-panel card"><span class="badge">Day ${daysSober()}</span><h2>Welcome Home</h2><p>This is the foundation build. Tap the front door to enter and test the room flow.</p><button class="primary" id="enterBtn">Enter Home</button></div></section>`;document.getElementById('enterDoor').onclick=enterHome;document.getElementById('enterBtn').onclick=enterHome;if(!state.settings.tutorialSeen)setTimeout(startTutorial,450);}
function enterHome(){state.location='hallway';render();}
function renderHallway(){setTitle('Hallway');stage.innerHTML=`<section class="scene slide-in"><div class="room-hint"><span class="pill">Tap a room</span><span class="pill">Day ${daysSober()}</span></div><div class="room-grid">${rooms.map(r=>`<button class="room-tile" data-room="${r.id}"><span>${r.icon}</span>${r.name}<small>${r.hint}</small></button>`).join('')}</div></section>`;stage.querySelectorAll('[data-room]').forEach(btn=>btn.onclick=()=>{state.location='room';state.room=btn.dataset.room;render();});}
function renderRoom(roomId){const room=rooms.find(r=>r.id===roomId);setTitle(room.name);stage.innerHTML=`<section class="room-view slide-in"><div class="room-wall"><div class="room-hint"><span class="pill">${room.icon} ${room.name}</span><span class="pill">Foundation</span></div><div class="placeholder ph-wall">Future wall item</div><div class="placeholder ph-big">Future main furniture</div><div class="placeholder ph-small">Future detail</div><div class="floor"></div></div><div class="room-actions"><button class="secondary" id="backHall">Back to Hallway</button><button class="primary" id="nextRoom">Next Room</button></div></section>`;document.getElementById('backHall').onclick=()=>{state.location='hallway';render();};document.getElementById('nextRoom').onclick=()=>{const i=rooms.findIndex(r=>r.id===roomId);state.room=rooms[(i+1)%rooms.length].id;render();};}
function renderJournal(){setTitle('Home Journal');stage.innerHTML=`<section class="scene"><div class="card view-card stack"><span class="badge">Foundation v0.1</span><h2>Your journey begins here.</h2><p class="muted">The journal is ready. In the next phase, every daily unlock and milestone will appear here.</p><div class="journal-list"><div class="card">Day 1 placeholder: First entry will go here.</div><div class="card">Milestones will be saved here.</div></div></div></section>`;}
function renderTimeMachine(){setTitle('Time Machine');stage.innerHTML=`<section class="scene"><div class="card view-card stack"><span class="badge">Preview only</span><h2>Preview sober day</h2><p class="muted">This foundation version only tests the setting. Future versions will transform the home.</p><div class="slider-row"><span>1</span><input id="previewDay" type="range" min="1" max="730" value="${state.settings.previewDay}"><span>730</span></div><h3>Day <span id="previewOut">${state.settings.previewDay}</span></h3><div class="split"><button class="secondary" data-day="30">30</button><button class="secondary" data-day="90">90</button><button class="secondary" data-day="180">180</button><button class="secondary" data-day="365">365</button></div></div></section>`;const slider=document.getElementById('previewDay');slider.oninput=()=>{state.settings.previewDay=Number(slider.value);document.getElementById('previewOut').textContent=slider.value;saveSettings();};stage.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.settings.previewDay=Number(b.dataset.day);saveSettings();renderTimeMachine();});}
function renderSettings(){setTitle('Settings');stage.innerHTML=`<section class="scene"><div class="card view-card stack"><h2>Setup</h2><div class="form-row"><label>Mode</label><select id="mode"><option value="auto">Automatic from sobriety date</option><option value="manual">Manual day count</option></select></div><div class="form-row"><label>Sobriety start date</label><input id="sobrietyDate" type="date" value="${state.settings.sobrietyDate}"></div><div class="form-row"><label>Manual sober day</label><input id="manualDay" type="number" min="1" value="${state.settings.manualDay}"></div><div class="form-row"><label>Preview calendar date</label><input id="previewDate" type="date" value="${state.settings.previewDate}"></div><button class="secondary" id="restartTutorial">Replay Tutorial</button><button class="secondary" id="resetData">Reset Saved Data</button></div></section>`;document.getElementById('mode').value=state.settings.mode;['mode','sobrietyDate','manualDay','previewDate'].forEach(id=>{document.getElementById(id).onchange=e=>{state.settings[id]=e.target.value;saveSettings();};});document.getElementById('restartTutorial').onclick=startTutorial;document.getElementById('resetData').onclick=()=>{localStorage.removeItem('wh_settings_v01');location.reload();};}
function startTutorial(){state.settings.tutorialSeen=true;saveSettings();modal.classList.remove('hidden');modal.innerHTML=`<div class="modal-inner stack"><span class="badge">Quick Tour</span><h2>How to use Welcome Home</h2><p>Tap the front door to enter. Tap any room to walk inside. Use the bottom buttons for Journal, Time Machine, and Settings.</p><button class="primary" id="closeTut">Got it</button></div>`;document.getElementById('closeTut').onclick=()=>modal.classList.add('hidden');}
helpBtn.onclick=startTutorial;navButtons.forEach(btn=>btn.onclick=()=>{state.view=btn.dataset.view;if(state.view==='home'&&!state.location)state.location='exterior';render();});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}render();
